Mensagens:
 PluginHabilitado:
  - '§bPlugin ScoreBoard Iniciado'
  - ''
 PluginDesabilitado:
  - ''
  - ''
 ComandoScoreHabilitada: "&aScoreboard habilitada."
 ComandoScoreDesabilitada: "&cScoreboard desabilitada."
