Porcentagem: 50

Licenca: AAAABBBBCCCC

MySQL:
  ativado: true
  user: 'root'
  password: 'pass'
  host: 'localhost'
  database: 'server'
 
# <player> nome do player
# & codigo para cor 
Itens:
  Espada:
    Mensagem: '&bMensagem privada ao jogador que executa o comando'
    #Quantidade De Almas Necessarias pra comprar
    Custo: 10
    Comandos:
      - 'give <player> diamond_sword 1'
      - 'say <player> Comprou uma espada de diamante!'
      
Prefix: "&e[MT_Almas] » "
TopAlmas:
  Formato: "   &f<posicao>° &7<nome> &8- &7<valor>"
  Tamanho: 5
      
Mensagens:
  SemPermissao: "&cVocê não possui permissão para isso!"
  SuasAlmas: "&bSuas Almas: &e<almas>"
  FormatoIncorreto: "&cFormato Incorreto, use apenas numeros!"
  VerAlmas: "&aAlmas do Jogador <player>: <almas>"
  VoceRecebeuAlmas: "§aVocê matou o jogador <player> e recebeu uma alma!"